export const FETCH_START = 'FETCH_START';
export const FETCH_END = 'FETCH_END';

export const SET_SESSION = 'SET_SESSION';

export const AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export const DEVICE_PLATFORM = 'DEVICE_PLATFORM';
export const DEVICE_LAYOUT = 'DEVICE_LAYOUT';
